# 1. Configuración de la Base de Datos (Render)
# Asegurate de que la URL empiece con jdbc:postgresql:// y no tenga el @ adentro
spring.datasource.url=jdbc:postgresql://dpg-d7f9q4t7vvec73a8e59g-a.oregon-postgres.render.com/inmobiliaria_db_e8yy
spring.datasource.username=inmobiliaria_db_e8yy_user
spring.datasource.password=jF868D2jT2JThvSBUKXWOEVWpDEkYJY1
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de JPA / Hibernate
# 'update' hace que Java cree las tablas en la nube automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# 3. Configuración del Servidor
server.port=8080

# 4. Configuración de Thymeleaf (para que no guarde cache mientras programas)
spring.thymeleaf.cache=false

# Esto evita que Spring intente manejar recursos que no le corresponden
spring.mvc.pathmatch.matching-strategy=ant_path_matcher